version: '3.8'
services:
  web:
    container_name: invoice_manager
    restart: always
    build: .
    networks:
      - db_network
      - web_network
      - db

  db:
    image: postgres:alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - web

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  postgres_data: