# Generated by Django 4.2.9 on 2024-02-02 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Card', 'Карта'), ('Bank Account', 'Платежный счет')], max_length=20, verbose_name='Тип платежа')),
                ('card_type', models.CharField(choices=[('MIR', 'Мир'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('OTHER', 'Другое')], max_length=20, verbose_name='Тип карты/Счета')),
                ('owner_name', models.CharField(max_length=100, verbose_name='ФИО владельца')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Лимит')),
            ],
            options={
                'verbose_name': 'Реквизит',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending Payment', 'Ожидает оплаты'), ('Paid', 'Оплачена'), ('Cancelled', 'Отменена')], max_length=20, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_detail', to='catalogs.paymentdetail')),
            ],
            options={
                'verbose_name': 'Заявка на оплату',
                'verbose_name_plural': 'Заявки на оплату',
            },
        ),
    ]
